CREATE TABLE TB_USER (
	ID_USER SERIAL PRIMARY KEY,
	EMAIL_USER VARCHAR(150) UNIQUE NOT NULL,
	PASSWORD_USER VARCHAR(150) NOT NULL,
	FIRST_NAME_USER VARCHAR(30) NOT NULL,
	LAST_NAME_USER VARCHAR(30),
	REGISTER_DT_USER TIMESTAMP NOT NULL,
	ROLE_USER VARCHAR(10) NOT NULL
);