CREATE TABLE TB_STATEMENT(
	ID_STATEMENT SERIAL PRIMARY KEY,
	DS_STATEMENT VARCHAR(100) NOT NULL,
	DT_STATEMENT TIMESTAMP NOT NULL,
	ID_USER INT NOT NULL,
	FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID_USER)
);